douban/helpdesk

- helpdesk/models/db/ticket.py
- helpdesk/views/api/index.py
- in-requirements.txt
- requirements.txt
ref: https://github.com/douban/helpdesk/commit/a01db750bb2fcbf5e8bf154d788c33469bddc99d#r39850258
> fix: use authlib.jose for jwt

- .github/release-drafter.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
* 新增一个 release drafter 的配置文件, 更新出来大概是这样 -> https://github.com/LeoQuote/test-github-action/releases
* 新增 release workflow , github release 的时候会把 release tag 推到 docker 上去
需要安装这个app -> https://github.com/LeoQuote/test-github-action/releases
我已经安装了
> add release drafter & release build

- helpdesk/models/db/ticket.py
- helpdesk/views/api/index.py
ref: https://github.com/douban/helpdesk/pull/15
> fix: usage of jose.jwt

- helpdesk/models/db/ticket.py
> Use HS256 alg for callback url

- .github/workflows/release-drafter.yml
the release drafter bot is deprecated
> Use release drafter action

- helpdesk/models/action.py
> update boolean field in form

- helpdesk/libs/notification.py
> Fix email send error

- frontend/src/components/HForm.vue
> pop up a modal asking user , go to ticket detail or stay here.

- frontend/src/components/HTicketDetail.vue
* check ticket status before actual approve/reject
* redirect user back to ticket detail after approve/reject
* hide dialog after reject
fix #37
> fix quick reject/approve handled multiple times bug

- Dockerfile
- in-requirements.txt
> avoid setuptools breaking change, fix build fail

- helpdesk/__init__.py
- helpdesk/config.py
- local_config.py.example
> add cors config

- helpdesk/libs/auth.py
> except DecodeError when jwt.decode token

- helpdesk/libs/auth.py
- helpdesk/views/auth/index.py
> get roles in current client_id only

- frontend/src/components/HForm.vue
- frontend/src/components/ResultHostTable.vue
- frontend/src/components/SubTabNoRecursive.vue
- helpdesk/libs/airflow.py
- helpdesk/models/provider/airflow.py
- requirements.txt
Add pretty log config for airflow dag log formatt
> Pretty log support

- frontend/src/components/SubTabNoRecursive.vue
> Fix subtab componet modal render error

- helpdesk/models/provider/airflow.py
If dag schema set a `status_filter` fields, it will replace default status filter. This filter will effect dag node showing. All nodes on the filter list status will not be showing in the result dag graph and log table.
> Airflow node status filter can be set by dag def

- frontend/src/components/HTicketDetail.vue
- frontend/src/components/HTicketResult.vue
- helpdesk/models/provider/airflow.py
1. fix old dag result can not load after dag file been modified error;
2. add auto refresh and fresh button on result page
> Fix old dag can not be loaded after dag altered

- frontend/src/components/HTicketDetail.vue
> Add a ticket final status

- helpdesk/config.py
- helpdesk/libs/notification.py
- templates/notification/mail/approval.j2
- templates/notification/mail/mark.j2
- templates/notification/mail/request.j2
fix #61 
```
Ticket: https://helpdesk.intra.douban.com/ticket/23
Parameters:
Request time: 2020-12-04 12:50:02 +0800 Fri
Reason: None
```
> add timezone & timeformat config

- helpdesk/libs/notification.py
- templates/notification/webhook/approval.j2
- templates/notification/webhook/mark.j2
- templates/notification/webhook/request.j2
本地测试时由于本地服务器的 timezone 是本地时区不是 UTC, 误以为已经转换了时区, 等上线的时候才发现实际上并没有转换
#61
> fix time not converted issue

- frontend/src/components/HForm.vue
> Fix backfill rerun error

- frontend/src/components/HForm.vue
之前的前端不会把 schema 内的 default value 写进去, 导致default value 异常.
> fix default value render

- frontend/src/components/HTicketList.vue
fix https://github.com/douban/helpdesk/issues/76
> Fix reject modal ticket id error

- requirements.txt
> Revert "chore(deps): bump urllib3 from 1.25.11 to 1.26.5"

- dev-requirements.txt
- helpdesk/libs/airflow.py
- helpdesk/models/provider/airflow.py
- requirements.txt
> Update airflow provider api to stable

- helpdesk/libs/airflow.py
> Fix airflow2.x not show log in helpdesk

- .doubanpde/Makefile
- .doubanpde/pde.yaml
- .gitignore
- deb-req.txt
- local_config.py.example
- requirements.txt
usage:
```bash
vim local_config.py
pdectl c
pdectl e
make -f .doubanpde/Makefile env
make -f .doubanpde/Makefile frontend
make -f .doubanpde/Makefile frontend-run
make -f .doubanpde/Makefile backtend-run
```
> Add approve workflow

- helpdesk/libs/spincycle.py
- helpdesk/models/provider/spincycle.py
> Use gojs for spincycle job graph shown

- frontend/pages/ticket/index.vue
根据状态 is_approved 判断是否已审批过，审批过的不能操作关闭
> fix list close button bug

- frontend/pages/ticket/_id/index.vue
- frontend/pages/ticket/index.vue
- helpdesk/libs/db.py
- helpdesk/libs/notification.py
- helpdesk/models/db/ticket.py
- helpdesk/views/api/index.py
- helpdesk/views/api/schemas.py
- templates/notification/mail/approval.j2
- templates/notification/webhook/approval.j2
ref：增加 ticket list search fix https://github.com/douban/helpdesk/issues/63
Jinja2 templates 渲染调整 http://onimaru.svc.douban/douban/helpdesk/issues/27000170/?query=is%3Aunresolved
展示的时间调整，notification的时间在这里调整
> Add ticket list search

- frontend/pages/policy/_id/index.vue
- helpdesk/libs/approver_provider.py
- helpdesk/models/db/ticket.py
- helpdesk/views/api/schemas.py
> add node approver type department

- frontend/pages/ticket/_id/index.vue
> ticket status closed without result button

- helpdesk/models/db/ticket.py
node_approvers  和 approvers 混淆了
> fix empty approvers

- .github/workflows/test.yml
- helpdesk/config.py
- helpdesk/libs/approver_provider.py
- helpdesk/libs/rest.py
- helpdesk/models/db/policy.py
- helpdesk/tests/conftest.py
- helpdesk/tests/test_auth.py
- helpdesk/tests/test_flow.py
- helpdesk/tests/test_policy.py
- helpdesk/tests/test_ticket.py
- requirements.txt
> complementary unit tests

- .github/workflows/test.yml
- .gitignore
- helpdesk/config.py
- helpdesk/libs/preprocess.py
- helpdesk/models/action.py
> add params preprocess

- helpdesk/views/auth/index.py
fix cannot convert 'URL' object to bytes
> fix redirect type error

- helpdesk/models/action_tree.py
- remove `pack.` prefix from action name
> Remove pack prefix of action name
