douban/helpdesk

helpdesk/__init__.py, helpdesk/libs/auth.py, helpdesk/views/auth/index.py
not tested
* 新增一个 `BearerAuthMiddleware`, 解析header 中的 auth 头, 然后验证token, 如果valid 就 set session
* 去掉无必要的 validate_email , 只需要oidc 那边有授权, 并且 aud 正常,  helpdesk 就认为是 valid .
=> add header auth

frontend/src/components/HHeader.vue, frontend/src/components/HTicketDetail.vue, frontend/src/components/HTicketList.vue, frontend/src/utils/HRequests.js, helpdesk/views/api/index.py
- notification use stringify force to string rather than showing `[object][object]`
- mark api setting ticket status is final status and will not be changed by `show result` button even they are different
- reject now can send a reason for user, the ticket `reason` field will show the reject reason rather than apply reason
- `details` link in ticket list link to `/tickt/xx` for better experience 
will resolve #26
=> Force notification use JSON stringify and reject can add reason

frontend/src/components/FormWidgets/SelectInput.vue, frontend/src/components/HForm.vue
taggable 使用户可以自己输入自定义的选项, 不需要这个选项
表单提交时提交按钮会暂时禁用, 在表单验证失败的场合, 提交按钮不会重新启用, 造成无法继续提交表单的问题.
=> delete taggable for select & make form submittable after validate failure

frontend/package-lock.json, frontend/package.json, frontend/src/components/HForm.vue, frontend/src/components/HTicketDetail.vue, frontend/src/components/HTicketResult.vue, frontend/src/components/Hdag.vue, frontend/src/components/ResultHostTable.vue, frontend/src/components/SubTabNoRecursive.vue, helpdesk/libs/airflow.py, helpdesk/libs/spincycle.py, helpdesk/models/action.py, helpdesk/models/provider/airflow.py, helpdesk/views/api/index.py
1. Add json schema validate for airflow provider
在dag的定义里增加一个params_json_schema的可选字段即可，ref: https://json-schema.org/
示例表示需要 f/c 字段，d/b/g 有且只能有一个,e是逗号分割的array字符串，每个字符串需要满足uri的标准格式，c必须满足pattern正则且最小长度为3等等约束.
因为dynamic-form的局限，对string之类的类型支持是前端转换之后做了校验，接收到的表单数据还是原来的表单数据（string only)
```python
'params_json_schema': {
"type": "object",
"properties": {
"a": {"type": "integer", "minimum": 3, "maximum": 30},
"b": {"type": "string"},
"c": {"type": "string", "pattern": "^'.+'$", "minLength": 3},
"d": {"type": "string"},
"e": {"type": "array", "items": {"type": "string", "format": "uri"},
"uniqueItems": True, "minItems": 1},
"f": {"type": "string"},
"g": {"type": "string"},
},
"oneOf": [
{"required": ["d"]},
{"required": ["b"]},
{"required": ["g"]}
],
"required": ["f", "c"]
},
```
2. …
=> Add json schema form verify && add dag for airflow && fix bugs

frontend/src/components/HForm.vue
json schema如果没有给这个字段写定义会导致取不到type，代码直接中断不会有任何报错。现在先检查字段是否存在然后再check。
=> Fix submit invalid while schema missing form field

requirements.txt
```
+ pip install --no-cache-dir -r requirements.txt
Collecting aiofiles==0.6.0
Downloading aiofiles-0.6.0-py3-none-any.whl (11 kB)
Collecting aiomysql==0.0.20
Downloading aiomysql-0.0.20-py3-none-any.whl (40 kB)
INFO: pip is looking at multiple versions of aiofiles to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 2) and PyMySQL==0.10.1 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The conflict is caused by:
The user requested PyMySQL==0.10.1
aiomysql 0.0.20 depends on PyMySQL<=0.9.2 and >=0.9
```
=> fix aiomysql & PyMySQL conflict

requirements.txt
pip 在升级到 20.3 后依赖控制有些 breaking change, 现在删除掉这些pin得基础包, 修复版本冲突
=> delete some pined versions to fix pip issue

frontend/src/components/DynamicForm.vue, frontend/src/components/FormWidgets/SelectInput.vue, frontend/src/components/HForm.vue, frontend/src/components/HTicketDetail.vue, frontend/src/components/HTicketList.vue
Fix #25 
Add a rerun link at ticket list. It will backfill params to the action form with this ticket's info. User can either edit value or just submit again.
=> Add rerun to ticket action

frontend/src/components/HSider.vue, helpdesk/models/action_tree.py, helpdesk/models/provider/__init__.py, helpdesk/models/provider/airflow.py, helpdesk/models/provider/errors.py, helpdesk/models/provider/st2.py
When some provider died, just notify user with notification instead of refuse to serve all provider's services.  We can still use healthy provider's action and ticket list (except we can not get log from crashed provider).
=> Isolate provider init

helpdesk/libs/auth.py
oauth client 用的是httpx, 所以配置文件里的代理格式跟着改了, requests 不支持这种格式, 所以直接改成 httpx
=> replace requests with httpx

helpdesk/models/action.py
观察了下，大部分审批阻塞的都是填入的app和实际app name不一致，光校验app字段意义不大
在获取获取节点审批人时，APP Owner为空的时候有两种场景：
1. 填入的 app 不一致，从而获取不到审批人
2. app 正确，但确实没有应用的owner作为审批人
因此 app owner 类型审批节点的审批人不能为空，为空时不能创建ticket，后续包含app owner的审批流均优先把owenr审批作为初始审批节点
=> add app approvers check before create ticket

helpdesk/models/provider/airflow.py
Do not show `skipped` workflow node in airflow cause flow chart broken (some node has no edge to them). This is a design before async_ssh_operator exists. Just show all nodes by default. If user needs hide some unused nodes, use `status_filter` in dag schema.
=> Show all workflow nodes by default

helpdesk/models/action.py, helpdesk/models/db/policy.py, helpdesk/models/db/ticket.py, helpdesk/tests/test_flow.py
bug: 修改工单关联的审批流，若还存在相关工单未审批完成的，则再审批可能会出错 (因为审批流程中会去再获取关联policy后处理，因此会拿到新配置的policy，从而导致节点流转异常)
调整为：
审批流执行均从工单 annotation 中获取节点信息，若出现更改，已存在工单按照原有方式审批，新提交工单会按照新配置的
=> Change node transation use annotation record

frontend/pages/ticket/index.vue, helpdesk/views/api/index.py
优化使用体验：
操作按钮以 status 为 pending 时才显示，不以 is_approved 判断，有时候有异常，is_approved 会没有数据导致前端显示异常
操作后状态未更新，在操作后 reload 列表使其更新
=> optimize frontend list operation response

helpdesk/libs/notification.py, helpdesk/views/api/schemas.py
1. 请求体中, 可选的值要设置 `= None` https://docs.pydantic.dev/latest/migration/#changes-to-pydanticbasemodel
2. orm_mode 已经凉了, 换成 model_validate
=> pydantic migration

helpdesk/views/api/schemas.py
params  dict 中可能存在不同类型的数据，不约束其子类型
https://docs.pydantic.dev/latest/usage/types/dicts_mapping/
=> Update NotifyMessage schema

helpdesk/views/api/index.py
在操作时都需要判断 ticket 当前是否能够进行操作，处于 pending 状态下才能操作 关闭/通过/拒绝
=> Update operate ticket check

frontend/components/DynamicForm.vue
When user filled a form then deleted a optional field, previously the field would be an empty string, which could be probelmatic.
This change can delete empty field, get rid of the problem.
=> When updating form, if field value is empty, delete the field.

frontend/pages/ticket/index.vue, helpdesk/views/api/index.py
默认展示自己的工单，管理员提供show all选项，选择后可查看所有的工单
=> default show own tickets and support show all for admin

.github/workflows/release.yml, .github/workflows/test.yml, frontend/components/ResultHostTable.vue, helpdesk/models/provider/airflow.py, helpdesk/tests/conftest.py
- show task running/no_status(-) etc status in task table
user often feels confused with the default task failed status (even when task is not scheduled to run)
=> Use real task status
